/**
 * Ulanzi AWTRIX API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Color } from './color';
import { ApiIndicator1PostRequestOneOf } from './apiIndicator1PostRequestOneOf';


/**
 * @type ApiIndicator1PostRequest
 * @export
 */
export type ApiIndicator1PostRequest = ApiIndicator1PostRequestOneOf | string;

