/**
 * Ulanzi AWTRIX API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MoodlightPostRequestOneOf1 } from './moodlightPostRequestOneOf1';
import { MoodlightPostRequestOneOf1Color } from './moodlightPostRequestOneOf1Color';
import { MoodlightPostRequestOneOf } from './moodlightPostRequestOneOf';


/**
 * @type MoodlightPostRequest
 * @export
 */
export type MoodlightPostRequest = MoodlightPostRequestOneOf | MoodlightPostRequestOneOf1 | string;

